############################################### CHANGE HERE ####################################################################
policy_path: "lw_benchhub/core/mdp/ckpt/loco.onnx"
use_gait: True
gait_parameters:
  frequencies: 1.5
  phase_offset: 0.5
  stance_ratio: 0.6
  kappa_gait_probs: 0.05
  desired_stance_width: 0.25
  desired_swing_height: 0.07

control_dt: 0.02
control_decimation: 4
################################################################################################################################


num_obs: 47
num_dof: 12
num_actions: 12
dof_idx: [ # change with num_dof
  0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11,
]
action_idx: [ # change with num_actions
  0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11,
]

kps: [ # change with urdf
  100, 100, 100, 150, 40, 40,
  100, 100, 100, 150, 40, 40,
  300, 300, 300,
  100, 100, 50, 50, 20, 20, 20,
  100, 100, 50, 50, 20, 20, 20
]
kds: [ # change with urdf
  2, 2, 2, 4, 2, 2,
  2, 2, 2, 4, 2, 2,
  3, 3, 3,
  2, 2, 2, 2, 1, 1, 1,
  2, 2, 2, 2, 1, 1, 1
]

default_angles: [ # change with urdf
  # -0.168,  0.0,  0.0, 0.4, -0.2, 0.0,
  # -0.168,  0.0,  0.0,  0.4, -0.2, 0.0
  # -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
  # -0.1,  0.0,  0.0,  0.3, -0.2, 0.0
  # 0, 0, 0,
  # 0, 0, 0, 0, 0, 0, 0,
  # 0, 0, 0, 0, 0, 0, 0
  -0.092, 0.0354, 0.000,0.311,-0.238,0.038,
  -0.092, 0.0354, 0.000,0.311,-0.238,0.038
]
# [6, 7, 10, 11, 14, 15, 18, 19, 22, 23, 30, 31]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 1]
max_cmd: [0.3, 0.3, 0.3]
cmd_clip: [0.1, 0.1, 0.1]
cmd_debug: [0., 0., 0.]

clip_observations: 100.
clip_actions: 100.

transition_time: 50
