############################################### CHANGE HERE ####################################################################
policy_path: "lw_benchhub/core/mdp/ckpt/squat.onnx"
use_gait: False

control_dt: 0.02
control_decimation: 4
################################################################################################################################


num_obs: 78 
num_dof: 29
num_actions: 12
dof_idx: [ # change with num_dof
  0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11,
  12, 13, 14,
  15, 16, 17, 18, 19, 20, 21,
  22, 23, 24, 25, 26, 27, 28
]
action_idx: [ # change with num_actions
  0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11,
]

kps: [ # change with urdf
  100, 100, 100, 150, 40, 40,
  100, 100, 100, 150, 40, 40,
  300, 300, 300,
  100, 100, 50, 50, 20, 20, 20,
  100, 100, 50, 50, 20, 20, 20
]
kds: [ # change with urdf
  2, 2, 2, 4, 2, 2,
  2, 2, 2, 4, 2, 2,
  3, 3, 3,
  2, 2, 2, 2, 1, 1, 1,
  2, 2, 2, 2, 1, 1, 1
]

default_angles: [ # change with urdf
  # -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
  # -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
  -0.092, 0.0354, 0.000,0.311,-0.238,0.038,
  -0.092, 0.0354, 0.000,0.311,-0.238,0.038,
  # -0.092, 0.0354, 0.000,0.511,-0.438,0.038,
  # -0.092, 0.0354, 0.000,0.511,-0.438,0.038,
  0, 0, 0,
  0, 0.3, 0, 1, 0, 0, 0,
  0, -0.3, 0, 1, 0, 0, 0
  # -1.5,0.5,-2.6,0.2,-1.2,0.15,1.2,
  # -1.5,-0.5,2.6,0.2,1.2,-0.15,-1.2
]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [1.0, 1.0]
max_cmd: [0.4, 0.5]
cmd_debug: [-1.5, .5]

clip_observations: 100.
clip_actions: 100.

transition_time: 10

# 'hip_pitch', 'hip_roll', 'hip_yaw', 'knee', 'ankle_pitch', 'ankle_roll',
# 'waist_yaw', 'waist_roll', 'waist_pitch',
# 'shoulder_pitch', 'shoulder_roll', 'shoulder_yaw', "elbow", "wrist_roll", "wrist_pitch", "wrist_yaw"