# Simulation parameters
simulation_duration: 1000.0
simulation_dt: 0.005
control_decimation: 4

# PD gains
# PD gains
kps: [150, 150, 150, 200, 40, 40,
      150, 150, 150, 200, 40, 40,
      250.0, 250.0, 250.0]
kds: [2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
      2.0, 2.0, 2.0, 4.0, 2.0, 2.0,
      5.0, 5.0, 5.0]

# Default joint angles for legs
default_angles: [-0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                 -0.1, 0.0, 0.0, 0.3, -0.2, 0.0,
                  0.0, 0.0, 0.0]
# Scaling factors
ang_vel_scale: 0.5
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.5]

# Number of actions and observations
num_actions: 15
num_obs: 516 # 516 # 86 * 6 (observation dimension * history length)
obs_history_len: 6

# Initial commands
cmd_init: [0.0, 0.0, 0.0]
height_cmd: 0.74
rpy_cmd: [0.0, 0.0, 0.0]
freq_cmd: 0.75

