'left_hip_pitch_joint': 0
'left_hip_roll_joint': 1
'left_hip_yaw_joint': 2
'left_knee_joint': 3
'left_ankle_pitch_joint': 4
'left_ankle_roll_joint': 5
'right_hip_pitch_joint': 6
'right_hip_roll_joint': 7
'right_hip_yaw_joint': 8
'right_knee_joint': 9
'right_ankle_pitch_joint': 10
'right_ankle_roll_joint': 11
'waist_yaw_joint': 12
'waist_roll_joint': 13
'waist_pitch_joint': 14
'left_shoulder_pitch_joint': 15
'left_shoulder_roll_joint': 16
'left_shoulder_yaw_joint': 17
'left_elbow_joint': 18
'left_wrist_roll_joint': 19
'left_wrist_pitch_joint': 20
'left_wrist_yaw_joint': 21
'left_hand_index_0_joint': 22
'left_hand_index_1_joint': 23
'left_hand_middle_0_joint': 24
'left_hand_middle_1_joint': 25
'left_hand_thumb_0_joint': 26
'left_hand_thumb_1_joint': 27
'left_hand_thumb_2_joint': 28
'right_shoulder_pitch_joint': 29
'right_shoulder_roll_joint': 30
'right_shoulder_yaw_joint': 31
'right_elbow_joint': 32
'right_wrist_roll_joint': 33
'right_wrist_pitch_joint': 34
'right_wrist_yaw_joint': 35
'right_hand_index_0_joint': 36
'right_hand_index_1_joint': 37
'right_hand_middle_0_joint': 38
'right_hand_middle_1_joint': 39
'right_hand_thumb_0_joint': 40
'right_hand_thumb_1_joint': 41
'right_hand_thumb_2_joint': 42
