robot_type: G1-Controller
default_task: PastryDisplay
features:
  observation.images.agentview_main:
    dtype: video
    shape: [480, 2400, 3]
    names: ["height", "width", "channel"]
    video_info:
      video.fps: 25.0
      video.codec: h264
      video.pix_fmt: yuv420p
      video.is_depth_map: false
      has_audio: false
  observation.state:
    dtype: float32
    shape: (31,)
    names:
      - base_x_joint
      - base_y_joint
      - base_yaw_joint
      - left_shoulder_pitch_joint
      - right_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - right_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - right_shoulder_yaw_joint
      - left_elbow_joint
      - right_elbow_joint
      - left_wrist_roll_joint
      - right_wrist_roll_joint
      - left_wrist_pitch_joint
      - right_wrist_pitch_joint
      - left_wrist_yaw_joint
      - right_wrist_yaw_joint
      - left_hand_index_0_joint
      - left_hand_middle_0_joint
      - left_hand_thumb_0_joint
      - right_hand_index_0_joint
      - right_hand_middle_0_joint
      - right_hand_thumb_0_joint
      - left_hand_index_1_joint
      - left_hand_middle_1_joint
      - left_hand_thumb_1_joint
      - right_hand_index_1_joint
      - right_hand_middle_1_joint
      - right_hand_thumb_1_joint
      - left_hand_thumb_2_joint
      - right_hand_thumb_2_joint
  action:
    dtype: float32
    shape: (31,)
    names:
      - base_x_joint
      - base_y_joint
      - base_yaw_joint
      - left_shoulder_pitch_joint
      - right_shoulder_pitch_joint
      - left_shoulder_roll_joint
      - right_shoulder_roll_joint
      - left_shoulder_yaw_joint
      - right_shoulder_yaw_joint
      - left_elbow_joint
      - right_elbow_joint
      - left_wrist_roll_joint
      - right_wrist_roll_joint
      - left_wrist_pitch_joint
      - right_wrist_pitch_joint
      - left_wrist_yaw_joint
      - right_wrist_yaw_joint
      - left_hand_index_0_joint
      - left_hand_middle_0_joint
      - left_hand_thumb_0_joint
      - right_hand_index_0_joint
      - right_hand_middle_0_joint
      - right_hand_thumb_0_joint
      - left_hand_index_1_joint
      - left_hand_middle_1_joint
      - left_hand_thumb_1_joint
      - right_hand_index_1_joint
      - right_hand_middle_1_joint
      - right_hand_thumb_1_joint
      - left_hand_thumb_2_joint
      - right_hand_thumb_2_joint
  episode_index:
    dtype: int64
    shape: [1]
    names: null
  frame_index:
    dtype: int64
    shape: [1]
    names: null
  index:
    dtype: int64
    shape: [1]
    names: null
  task_index:
    dtype: int64
    shape: [1]
    names: null
