robot_type: LeRobot-Abs
default_task: PnPOrange
features:
  observation.images.agentview_main:
    dtype: video
    shape: [480, 960, 3]
    names: ["height", "width", "channel"]
    video_info:
      video.fps: 30.0
      video.codec: h264
      video.pix_fmt: yuv420p
      video.is_depth_map: false
      has_audio: false
  observation.state:
    dtype: float32
    shape: (6,)
    names:
      - shoulder_pan.pos
      - shoulder_lift.pos
      - elbow_flex.pos
      - wrist_flex.pos
      - wrist_roll.pos
      - gripper.pos
  action:
    dtype: float32
    shape: (6,)
    names:
      - shoulder_pan.pos
      - shoulder_lift.pos
      - elbow_flex.pos
      - wrist_flex.pos
      - wrist_roll.pos
      - gripper.pos
  episode_index:
    dtype: int64
    shape: [1]
    names: null
  frame_index:
    dtype: int64
    shape: [1]
    names: null
  index:
    dtype: int64
    shape: [1]
    names: null
  task_index:
    dtype: int64
    shape: [1]
    names: null
