name: lwlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pinocchio=3.6.0
  - pip
  - pip:
    - --extra-index-url https://mirrors.aliyun.com/pypi/simple/
    - torch==2.5.1
    - torchvision==0.20.1
    - scipy==1.15.3
    - dex_retargeting==0.5.0
    - meshcat==0.3.2
    - casadi==3.7.0
    - vuer[all]==0.0.60
    - pin-pink==3.1.0
    - onnxruntime
    - numpy
    