name: lwlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pinocchio=3.6.0
  - pip
  - pip:
    - --extra-index-url https://mirrors.aliyun.com/pypi/simple/
    - torch==2.5.1
    - torchvision==0.20.1
    - scipy==1.15.3
    - dex_retargeting==0.5.0
    - onnxruntime
    - numpy
    