robot_type: Piper-Abs
default_task: LiftObj
features:
  observation.images.agentview_all:
    dtype: video
    shape: [480, 480, 3]
    names: ["height", "width", "channel"]
    video_info:
      video.fps: 30.0
      video.codec: h264
      video.pix_fmt: yuv420p
      video.is_depth_map: false
      has_audio: false
  observation.images.agentview_hand:
    dtype: video
    shape: [480, 480, 3]
    names: ["height", "width", "channel"]
    video_info:
      video.fps: 30.0
      video.codec: h264
      video.pix_fmt: yuv420p
      video.is_depth_map: false
      has_audio: false
  observation.state:
    dtype: float32
    shape: (8,)
    names:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - finger_joint_left
      - finger_joint_right
  action:
    dtype: float32
    shape: (8,)
    names:
      - ee_delta_x   
      - ee_delta_y   
      - ee_delta_z
      - ee_delta_quat_w
      - ee_delta_quat_x
      - ee_delta_quat_y
      - ee_delta_quat_z
      - gripper_cmd
  episode_index:
    dtype: int64
    shape: [1]
    names: null
  frame_index:
    dtype: int64
    shape: [1]
    names: null
  index:
    dtype: int64
    shape: [1]
    names: null
  task_index:
    dtype: int64
    shape: [1]
    names: null
