robot_type: x7s
default_task: Lift Cube
features:
  observation.images.left_hand_camera:
      dtype: video
      shape: [480, 480, 3]
      names: ["height", "width", "channel"]
      video_info:
        video.fps: 25.0
        video.codec: h264
        video.pix_fmt: yuv420p
        video.is_depth_map: false
        has_audio: false

  observation.images.first_person_camera:
      dtype: video
      shape: [480, 480, 3]
      names: ["height", "width", "channel"]
      video_info:
        video.fps: 25.0
        video.codec: h264
        video.pix_fmt: yuv420p
        video.is_depth_map: false
        has_audio: false


  observation.state:
    dtype: float32
    shape: (8,)
    names:
      - x
      - y
      - z
      - qw
      - qx
      - qy
      - qz
      - gripper
  action:
    dtype: float32
    shape: (8,)
    names:
      - dx
      - dy
      - dz
      - d_qw
      - d_qx
      - d_qy
      - d_qz
      - gripper
  episode_index:
    dtype: int64
    shape: [1]
    names: null
  frame_index:
    dtype: int64
    shape: [1]
    names: null
  index:
    dtype: int64
    shape: [1]
    names: null
  task_index:
    dtype: int64
    shape: [1]
    names: null
