_base_: [rl_base]
task: LiftObj                # Task name
robot: Lerobot-RL                 # Robot type
layout: robocasakitchen-9-8  # Scene layout
usd_simplify: true # USD simplify enable
variant: State
max_iterations: 2         # Max RL policy training iterations
num_envs: 10                 # Number of environments to simulate
