_base_: [rl_base]
task: LiftObj                # Task name
robot: Lerobot-RL                 # Robot type
layout: robocasakitchen-9-8  # Scene layout
num_envs: 512
usd_simplify: true # USD simplify enable
variant: State
enable_cameras: false
check_success: true
max_iterations: 1601
