_base_:
  - rl_base
task: LiftObj                # Task name
robot: LeRobot-RL                 # Robot type
layout: robocasakitchen-9-8  # Scene layout
rl: LeRobotLiftObjStateRL
num_envs: 512
usd_simplify: true # USD simplify enable
enable_cameras: false
