_base_:
  - teleop_base
dataset_file: ./datasets/dataset.hdf5
device: cpu
disable_fabric: false
enable_cameras: false
enable_debug_log: false
enable_multiple_viewports: false
enable_optimization: true
enable_pinocchio: false
first_person_view: false
layout: robocasakitchen-2-2
max_object_placement_retry: 3
max_scene_retry: 4
num_demos: 1
num_envs: 1
object_projects: []
record: true
robot: G1-Controller-DecoupledWBC
robot_scale: 1.0
save_video: false
seed: 0
sensitivity: 1.0
sources:
- objaverse
- lightwheel
- aigen_objs
step_hz: 50
task: OpenDishwasher
teleop_device: vr-controller
usd_simplify: false
use_fabric: false
video_fps: 30
video_save_dir: ./videos
