# =========================
# Basic Settings
# =========================
disable_fabric: false
num_envs: 1
device: cpu
sensitivity: 1.0
step_hz: 50

# =========================
# Robot Settings
# =========================
robot: PandaOmron-Rel
robot_scale: 1.0

# =========================
# Task & Scene Settings
# =========================
task: RobocasaBaseTask
scene_backend: robocasa
task_backend: robocasa
debug_assets: null
layout: robocasakitchen
sources:
  - objaverse
  - lightwheel
  - aigen_objs
object_projects: []
usd_simplify: false
seed: 0

# =========================
# Data Collection Settings
# =========================
record: false
dataset_file: ./datasets/dataset.hdf5
num_demos: 1
enable_debug_log: false
continue_teleop_after_success: false

# =========================
# Teleoperation Device Settings
# =========================
enable_pinocchio: false
teleop_device: keyboard
relative_control: false
first_person_view: false
enable_rendering_optimization: true
enable_multiple_viewports: false
action_delay_async: false
action_delay_time_s: 0
action_delay_type: fixed
action_buffer_size: 100


# =========================
# Video Saving Settings
# =========================
enable_cameras: false
save_video: false
video_save_dir: ./videos
video_fps: 30

# =========================
# Object Placement Retry Settings
# =========================
max_scene_retry: 4
max_object_placement_retry: 3

resample_objects_placement_on_reset: true
resample_robot_placement_on_reset: true