"left_hip_pitch_joint": 0
"right_hip_pitch_joint": 1
"waist_yaw_joint": 2
"left_hip_roll_joint": 3
"right_hip_roll_joint": 4
"waist_roll_joint": 5
"left_hip_yaw_joint": 6
"right_hip_yaw_joint": 7
"waist_pitch_joint": 8
"left_knee_joint": 9
"right_knee_joint": 10
"left_shoulder_pitch_joint": 11
"right_shoulder_pitch_joint": 12
"left_ankle_pitch_joint": 13
"right_ankle_pitch_joint": 14
"left_shoulder_roll_joint": 15
"right_shoulder_roll_joint": 16
"left_ankle_roll_joint": 17
"right_ankle_roll_joint": 18
"left_shoulder_yaw_joint": 19
"right_shoulder_yaw_joint": 20
"left_elbow_joint": 21
"right_elbow_joint": 22
"left_wrist_roll_joint": 23
"right_wrist_roll_joint": 24
"left_wrist_pitch_joint": 25
"right_wrist_pitch_joint": 26
"left_wrist_yaw_joint": 27
"right_wrist_yaw_joint": 28
"left_hand_index_0_joint": 29
"left_hand_middle_0_joint": 30
"left_hand_thumb_0_joint": 31
"right_hand_index_0_joint": 32
"right_hand_middle_0_joint": 33
"right_hand_thumb_0_joint": 34
"left_hand_index_1_joint": 35
"left_hand_middle_1_joint": 36
"left_hand_thumb_1_joint": 37
"right_hand_index_1_joint": 38
"right_hand_middle_1_joint": 39
"right_hand_thumb_1_joint": 40
"left_hand_thumb_2_joint": 41
"right_hand_thumb_2_joint": 42